export enum NotificationAction {
  FOLLOW_REQUEST = 'FOLLOW_REQUEST',
  FOLLOW_ACCEPTED = 'FOLLOW_ACCEPTED',
  FOLLOW_REJECTED = 'FOLLOW_REJECTED',
  MENTION_COMMENT = 'MENTION_COMMENT',
  MENTION_POST = 'MENTION_POST',
}
